apiVersion: v1
kind: Pod
metadata:
  name: debug-demo
  namespace: default
  labels:
    app: debug-demo
spec:
  containers:
  - name: main
    image: "test:v1"
    command:
      - "/usr/bin/env"
    args:
      - "/bin/bash"
      - "-c"
      - "while true;do echo sleep; sleep 2; done"
  restartPolicy: Always